# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - run: echo "first ci cd"
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
